### ISSUE TITLE
Fix needed to access site basic info?

### ISSUE THREAD

**Issue by paulusm** [lucjon/Py-StackExchange#35]
In API 2.2, the /info path now optionally returns the Site basic information: name, launch_date, logos etc:
https://api.stackexchange.com/docs/types/site
This doesn't seem to be reflected in the Py Stackexchange Site object, though - unless I'm missing it.
I had a look at where to make a code change, but wasn't sure if this should be the on the Statistics or Site objects.

**Comment by lucjon** [comment]
Hello,

Thanks for bringing this to my attention. I've reshuffled the methods used for accessing Statistics, etc. information to better reflect the current state of the API. The stats() method is now just an alias to info() - it is kept around for compatibility reasons. It also now takes an optional `site` parameter which, if True, requests the basic site metadata you are asking about by exposing the `site` field of the API's `info` type, albeit under the name `site_definition` due to an unfortunate choice of internal field name back when the library was first written.

This information was previously accessible via StackAuth; I have moved some code around to allow it to be used from the main API as well.
