### ISSUE TITLE
How to get quota_remaining

### ISSUE THREAD

**Issue by educalleja** [lucjon/Py-StackExchange#45]
This might be a stupid question but I have been trying for more than an hour without success. 
I have an API key and I would like to retrieve the remaining quota. Is this feature implemented?
Strangely, I can do the following to obtain the total number of questions for an specific language for a day:

    so = stackexchange.Site(stackexchange.StackOverflow, STACKEXCHANGE_API_KEY)
    qs = so.search(tagged='python', fromdate=1455926400, todate=1456012800, filter='!9YdnSPuG8')
    print qs.total  # 420
    print qs.has_more # True

While the following instructions do not work.
    print qs.quota_remaining  # Error
    print qs.quota_mas #  Error

The JSON results for this query can be seen [here](https://api.stackexchange.com/2.2/search?fromdate=1455926400&todate=1456012800&order=desc&sort=activity&tagged=python&site=stackoverflow&filter=!9YdnSPuG8).

By the way this library is awesome.

**Comment by lucjon** [comment]
Hello,

Sorry, this isn't well-documented, but the rate limit fields are accessible via the Site (`so`) object rather than on the results object itself, for compatibility with older versions of the library. Using `so.rate_limit` in your example will give a tuple `(quota_remaining, quota_max)`, and there are also convenience properties `so.requests_used` and `so.requests_left`. These properties only exist after the first request has been made.

Thanks :)
